certificate-tool.pdf: certificate-tool.tex
	pdflatex certificate-tool.tex
	pdflatex certificate-tool.tex
	rm -f *.aux *.log *.synctex.gz *.toc

clean:
	rm -f certificate-tool.pdf *.aux *.log *.synctex.gz *.toc
